source 'https://rubygems.org'

gem 'aruba',         '~> 0.9.0'
gem 'awesome_print', '~> 1.6', '>= 1.6.1'
gem 'cucumber',      '~> 1.3.0'
gem 'curb',          '~> 0.8.0'
gem 'diffy',         '~> 3.0', '>= 3.0.7'
gem 'fog',           '~> 1.34.0'
gem 'hashie',        '~> 3.4.0'
gem 'json_spec',     '~> 1.1', '>= 1.1.4'
gem 'pg',            '~> 0.18.0'
gem 'rspec',         '~> 3.3.0'
