FROM java
MAINTAINER Michael Barton, mail@michaelbarton.me.uk

RUN wget --quiet https://github.com/downloads/stephenh/fakesdb/fakesdb-standalone-2.4.jar
CMD ["java", "-jar", "fakesdb-standalone-2.4.jar"]
