#!/bin/bash

set -o errexit

if [[ -z "$CI" ]]; then
  cp ~/.aws_event_api_dev $1
else
  set -o nounset
  echo AWS_ACCESS_KEY=${AWS_ACCESS_KEY} >  $1
  echo AWS_SECRET_KEY=${AWS_SECRET_KEY} >> $1
fi

chmod 400 $1
