#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), '..'))

require 'features/support/docker'
require 'features/support/postgres'

require 'irb'
require 'irb/completion'

IRB.start
