#!/bin/bash

set -o errexit

if [ -z "${POSTGRES_USER}" ]; then
	export POSTGRES_USER=${RDS_USERNAME}
fi

if [ -z "${POSTGRES_PASSWORD}" ]; then
	export POSTGRES_PASSWORD=${RDS_PASSWORD}
fi

if [ -z "${POSTGRES_NAME}" ]; then
	export POSTGRES_NAME=${RDS_DB_NAME}
fi

if [ -z "${POSTGRES_HOST}" ]; then
	export POSTGRES_HOST="//${RDS_HOSTNAME}:${RDS_PORT}"
fi
