#!/bin/bash

set -o errexit

if [ -z "${PGUSER}" ]; then
	export PGUSER=${RDS_USERNAME}
fi

if [ -z "${PGPASSWORD}" ]; then
	export PGPASSWORD=${RDS_PASSWORD}
fi

if [ -z "${PGDATABASE}" ]; then
	export PGDATABASE=${RDS_DB_NAME}
fi

if [ -z "${PGHOST}" ]; then
	export PGHOST="${RDS_HOSTNAME}"
fi

if [ -z "${PGPORT}" ]; then
	export PGPORT="${RDS_PORT}"
fi
